# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Create Stable Release

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      prerelease:
        description: 'The release should be an experimental release'
        default: 'NO'
        required: true

permissions:
  contents: read

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - uses: addnab/docker-run-action@4f65fabd2431ebc8d299f8e5a018d79a769ae185 # v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io
          image: eclipse-temurin:17-ubi9-minimal
          options: >- 
            -v ${{ github.workspace }}:/work 
            -e GITHUB_USER=gocd
            -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
            -e PRERELEASE=${{ github.event.inputs.prerelease }}
          run: |
            microdnf install -y git findutils
            git config --global --add safe.directory /work
            cd work
            ./gradlew verifyExpRelease githubRelease

